/*
 * This file is generated by jOOQ.
 */
package io.github.sola97.sesearch.dataobject;


import io.github.sola97.sesearch.dataobject.social_engineering.SocialEngineeringT;

import java.util.Arrays;
import java.util.List;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>social_engineering</code>.
     */
    public final SocialEngineeringT SOCIAL_ENGINEERING = SocialEngineeringT.SOCIAL_ENGINEERING;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.<Schema>asList(
                SocialEngineeringT.SOCIAL_ENGINEERING);
    }
}
