/*
 * This file is generated by jOOQ.
 */
package io.github.sola97.sesearch.dataobject.social_engineering;


import io.github.sola97.sesearch.dataobject.social_engineering.tables.QqT;
import io.github.sola97.sesearch.dataobject.social_engineering.tables.WeiboT;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in social_engineering.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index QQ_PHONE = Internal.createIndex(DSL.name("phone"), QqT.QQ, new OrderField[]{QqT.QQ.PHONE}, false);
    public static final Index WEIBO_PHONE = Internal.createIndex(DSL.name("phone"), WeiboT.WEIBO, new OrderField[]{WeiboT.WEIBO.PHONE}, false);
    public static final Index QQ_QQ = Internal.createIndex(DSL.name("qq"), QqT.QQ, new OrderField[]{QqT.QQ.QQ_}, false);
    public static final Index WEIBO_UID = Internal.createIndex(DSL.name("uid"), WeiboT.WEIBO, new OrderField[]{WeiboT.WEIBO.UID}, false);
}
