/*
 * This file is generated by jOOQ.
 */
package io.github.sola97.sesearch.dataobject.social_engineering;


import io.github.sola97.sesearch.dataobject.social_engineering.tables.QqT;
import io.github.sola97.sesearch.dataobject.social_engineering.tables.WeiboT;


/**
 * Convenience access to all tables in social_engineering.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>social_engineering.qq</code>.
     */
    public static final QqT QQ = QqT.QQ;

    /**
     * The table <code>social_engineering.weibo</code>.
     */
    public static final WeiboT WEIBO = WeiboT.WEIBO;
}
