/*
 * This file is generated by jOOQ.
 */
package io.github.sola97.sesearch.dataobject.social_engineering.tables.records;


import io.github.sola97.sesearch.dataobject.social_engineering.tables.QqT;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class QqRecord extends TableRecordImpl<QqRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>social_engineering.qq.qq</code>.
     */
    public void setQq(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>social_engineering.qq.qq</code>.
     */
    public String getQq() {
        return (String) get(0);
    }

    /**
     * Setter for <code>social_engineering.qq.phone</code>.
     */
    public void setPhone(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>social_engineering.qq.phone</code>.
     */
    public String getPhone() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return QqT.QQ.QQ_;
    }

    @Override
    public Field<String> field2() {
        return QqT.QQ.PHONE;
    }

    @Override
    public String component1() {
        return getQq();
    }

    @Override
    public String component2() {
        return getPhone();
    }

    @Override
    public String value1() {
        return getQq();
    }

    @Override
    public String value2() {
        return getPhone();
    }

    @Override
    public QqRecord value1(String value) {
        setQq(value);
        return this;
    }

    @Override
    public QqRecord value2(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public QqRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QqRecord
     */
    public QqRecord() {
        super(QqT.QQ);
    }

    /**
     * Create a detached, initialised QqRecord
     */
    public QqRecord(String qq, String phone) {
        super(QqT.QQ);

        setQq(qq);
        setPhone(phone);
    }
}
