/*
 * This file is generated by jOOQ.
 */
package io.github.sola97.sesearch.dataobject.social_engineering.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WeiboPO implements Serializable {

    private static final long serialVersionUID = 1L;

    private String phone;
    private String uid;

    public WeiboPO() {
    }

    public WeiboPO(WeiboPO value) {
        this.phone = value.phone;
        this.uid = value.uid;
    }

    public WeiboPO(
            String phone,
            String uid
    ) {
        this.phone = phone;
        this.uid = uid;
    }

    /**
     * Getter for <code>social_engineering.weibo.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>social_engineering.weibo.phone</code>.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>social_engineering.weibo.uid</code>.
     */
    public String getUid() {
        return this.uid;
    }

    /**
     * Setter for <code>social_engineering.weibo.uid</code>.
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WeiboPO (");

        sb.append(phone);
        sb.append(", ").append(uid);

        sb.append(")");
        return sb.toString();
    }
}
